export enum ActionType {
  // alerts
  ALERT_SUCCESS = "ALERT_SUCCESS",
  ALERT_ERROR = "ALERT_ERROR",
  ALERT_CLEAR = "ALERT_CLEAR",

  // users
  USERS_SIGNUP_REQUEST = 'USERS_SIGNUP_REQUEST',
  USERS_SIGNUP_SUCCESS = 'USERS_SIGNUP_SUCCESS',
  USERS_SIGNUP_FAILURE = 'USERS_SIGNUP_FAILURE',

  USERS_SIGNIN_REQUEST = 'USERS_SIGNIN_REQUEST',
  USERS_SIGNIN_SUCCESS = 'USERS_SIGNIN_SUCCESS',
  USERS_SIGNIN_FAILURE = 'USERS_SIGNIN_FAILURE',
    
  USERS_SIGNOUT = 'USERS_SIGNOUT',
}