export enum ErrorType {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  USER_EXISTS = "USER_EXISTS",
  USER_LOGIN_EXISTS = "USER_LOGIN_EXISTS",
  USER_PASSWORD_INCORRECT = "USER_PASSWORD_INCORRECT",

  CHAT_NOT_FOUND = "CHAT_NOT_FOUND",
  CHAT_NOT_MEMBER = "CHAT_NOT_MEMBER",
  CHAT_MESSAGE_NOT_FOUND = "CHAT_MESSAGE_NOT_FOUND",
  CHAT_MESSAGE_NOT_OWNER = "CHAT_MESSAGE_NOT_OWNER",
}
